databases:
  - name: bugget-app
    databaseName: bugget_app_7i7u
    user: bugget_app_7i7u_user

services:
  - type: web
    name: Budget-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bugget-app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false